Develop - initial commit
jokindy/java-explore-with-me pull request #2
Opened 2022-09-20 14:33 UTC by jokindy

2022-09-21 06:22 UTC, Frilock requested changes
Добрый день, часть оставил ряд комментариев к работе, кроме того хотел бы предложить для ваших сервисов написать unit тесты, чтобы все было красиво.
Из основного, для полей в моделях указывайте размер и флаг nullable = false, а так же поправьте pom файлы.

2022-09-21 06:22 UTC, Frilock commented on server/pom.xml
> +            <version>3.1.0</version>
Версии библиотек нужно подключать в корневом pom файле, чтобы точка добавления зависимостей была в одном месте, в секции dependencyManager. Кроме того, саму версию предлагаю вынести в properties, чтобы изменение версии было более простой задачей.

2022-09-21 06:22 UTC, Frilock commented on server/pom.xml
> +                    <source>11</source>
Вы вроде в properties версию указываете, а тут все равно числом ее проставляете

2022-09-21 06:22 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/ServerApp.java
> +    public ModelMapper modelMapper() {
Вообще обычно данный в данном файле располагается только функция main, а зачем Вам создавать ModelMapper через использование аннотации Bean? Почему просто через new не использовать, там где вам нужно

2022-09-21 06:22 UTC, Frilock commented on stats/src/main/java/ru/practicum/explorewithme/stat/StatsRepo.java
> +public interface StatsRepo extends JpaRepository<EndpointHit, Long> {
Предлагаю отказаться от таких сокращений, давайте лучше StatsRepository назовем, просто вообще в Java не очень принята культура сокращений в именования переменных, классов и т.д.

2022-09-21 06:22 UTC, Frilock commented on stats/src/main/java/ru/practicum/explorewithme/stat/StatsRepo.java
> +    String QUERY_NON_UNIQUE = "select distinct(e.uri) as uri, count(e.app) as hits, e.app as app " +
А  почему у данных констант отсутствует модификатор доступа? Вообще по хорошему надо бы private static final

2022-09-21 06:22 UTC, Frilock commented on stats/src/main/java/ru/practicum/explorewithme/stat/StatsRepo.java
> +package ru.practicum.explorewithme.stat;
Как общий совет, предлагаю Вам установить в IDEA плагин sonarlint - это статический анализатор кода, он подсвечивает те места, где возможны какие то ошибки и подсказывает ряд хороших практик

2022-09-21 06:22 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/compilation/admin/CompilationAdminController.java
> +    @PostMapping()
Вообще пустые скобки не нужны в аннотации если в value ничего нет, лучше бы их убрать

2022-09-21 06:22 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/category/Category.java
> +    private String name;
Смотрите, общий комментарий к другим entity, вообще поля лучше аннотировать аннотацией Column, где указать размер поля. Поскольку по стандарту задается размер в 255 символом, но например, для имени этого много, а для описания может быть мало, вы должны управлять размером полей с использованием данных аннотаций, так же там есть дополнительные флаги, например, может ли быть поле nullable или нет

2022-09-21 06:22 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/category/admin/CategoryAdminController.java
> +        Category category = modelMapper.map(categoryDto, Category.class);
Мне кажется что маппинг лучше перенести в сервис слой

2022-09-21 06:22 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/category/admin/CategoryAdminService.java
> +    private CategoryPublicService categoryPublicService;
А почему одно поле final, а другое нет? Вы можете сделать их оба final а над классом вместо @AllArgsConstructor повесить RequiredArgsConstructor

2022-09-21 06:22 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/category/common/CategoryPublicService.java
> +            log.warn("CATEGORY PUBLIC SERVICE - ModelNotFoundException");
Смотрите, вы бросаете исключение, а в лог пишете warn, это выглядит странно, на мой взгляд, лучше error писать

2022-09-21 06:22 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/category/common/CategoryPublicService.java
> +        log.debug("CATEGORY PUBLIC SERVICE - checking category id: {} is exists", categoryId);
А зачем вы в логе везде добавляете название класса, это выглядит странно, вообще в логе лучше писать что то осмысленное, или тогда вообще его лучше убирать. Какой смысл в каждом методе по цепочке писать, что вы в него попали, это ведь тоже какая никакая но нагрузка

2022-09-21 06:22 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/event/Event.java
> +    @ManyToOne(fetch = FetchType.EAGER)
А зачем сразу EAGER делать? Данное поле всегда нужно?

2022-09-21 06:22 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/event/dto/AdminUpdateEventDto.java
> +
Зачем столько пустых строчек?

2022-09-21 06:22 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/event/Event.java
> +    public int hashCode() {
Предлагаю лучше стандартным hashCode пользоваться, который IDEA генерирует (code - generate...)

2022-09-21 06:22 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/event/EventFilter.java
> +            if (event.getState().equals(state)) {
Это такой комментарий с советом больше, лучше вообще использовать null safe equals, Objects.equals(o1, o2), чтобы быть уверенным в отсутствии NPE

2022-09-27 19:27 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/category/common/CategoryPublicService.java
> +        log.debug("CATEGORY PUBLIC SERVICE - checking category id: {} is exists", categoryId);
в пропертях можно поставить уровень логирования выше debug и проблема решится сама собой
p.s. с названиями классов согласен

2022-09-29 20:46 UTC, jokindy commented on stats/src/main/java/ru/practicum/explorewithme/stat/StatsRepo.java
> +    String QUERY_NON_UNIQUE = "select distinct(e.uri) as uri, count(e.app) as hits, e.app as app " +
в интерфейсах каждая переменная уже по определению private static final

2022-09-29 21:15 UTC, jokindy commented
Тесты не успел сделать, так как занимался эвакуацией себя в другую страну

2022-09-30 19:56 UTC, Frilock requested changes
Добрый вечер, вижу что поправили мои комментарии, я бы вообще от Вас все таки тестов вашего кода хотел увидеть, это полезно и правильно, но не могу с Вас такого требовать. Давайте если писать их не хотите, пришлите мне работу еще раз и я ее приму. Либо все таки жду работу с тестами. Мб у Вас еще что то всплывет

2022-10-04 17:56 UTC, jokindy commented
C тестами совсем к сожалению не успеваю, хотя бы порефакторил немного)

2022-10-04 18:21 UTC, Frilock approved these changes
Принято

2022-10-07 12:22 UTC, merged