feat: add comments
jokindy/java-explore-with-me pull request #3
Opened 2022-09-30 14:38 UTC by jokindy

Дисклеймер - делал в большой спешке, возможно вы заметите костыли и/или сомнительные решения по ходу проверки - я внимательно отнесусь ко всем замечаниям, не щадите, я все исправлю

2022-10-01 12:25 UTC, aturin236 reviewed
Задал несколько вопросов. Посмотри, пожалуйста

2022-10-01 12:25 UTC, aturin236 commented on server/src/main/java/ru/practicum/explorewithme/comment/Comment.java
> +    private long eventId;
Зачем нужны отдельные поля с id автора и эвента, когда есть полноценные поля автора и эвента?

2022-10-01 12:25 UTC, aturin236 commented on server/src/main/java/ru/practicum/explorewithme/comment/Comment.java
> +    public boolean equals(Object o) {
через lombok не получится реализовать equals и hashcode?

2022-10-01 12:25 UTC, aturin236 commented on server/src/main/java/ru/practicum/explorewithme/comment/admin/CommentAdminController.java
> +    public CommentDto publishComment(@PathVariable long commentId) {
общий путь "/admin/comments/{commentId}" у всех контроллеров можно вынести в шапку через @RequestMapping

2022-10-01 12:25 UTC, aturin236 commented on server/src/main/java/ru/practicum/explorewithme/comment/common/CommentPublicService.java
> +            return pageMaker.getPage(comments, pageable).getContent();
Не очень понял. Если мы уже имеем лист коментов, зачем через pageMaker прогонять? Не тоже самое будет?

И по этой же теме: я правильно понимаю, что если в репозитории сделать еще метод findAllByEventIdAndStateAndPositive, то можно результат одним запросом получить без фильтрации стрима?

2022-10-01 12:25 UTC, aturin236 commented on server/src/main/java/ru/practicum/explorewithme/comment/common/CommentPublicService.java
> +        if (optionalComment.isEmpty()) {
по-моему, здесь зайдет .orElseThrow()

2022-10-01 12:25 UTC, aturin236 commented on server/src/main/java/ru/practicum/explorewithme/comment/common/CommentPublicService.java
> +            useful++;
Для себя вопрос: мы получили ссылку на комент, в отдельной переменной изменили useful, потом сохранили изменение в базе, но useful в ссылке comment остался прежним. Не может выйти так, что если где-то в другом месте будет эта ссылка использована, то там получат старый useful?

2022-10-01 12:25 UTC, aturin236 commented on server/src/main/java/ru/practicum/explorewithme/comment/user/CommentUserController.java
> +        mapper.map(commentUserService.getComment(dto.getId()), comment);
может логику апдейта в сервисе разместить? Иначе в слое контроллеров появляется объект доменной логики (new Comment())

2022-10-01 12:25 UTC, aturin236 commented on server/src/main/java/ru/practicum/explorewithme/comment/user/CommentUserService.java
> +        entityManager.refresh(comment);
Без refresh что-то пойдет не так?

2022-10-01 12:25 UTC, aturin236 commented on server/src/main/java/ru/practicum/explorewithme/event/Event.java
> +    private List<Compilation> compilations;
тут действительно полезно знать в какие компиляции входит эвент? Может оставить только в компиляциях список эвентов?

2022-10-02 17:37 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/Comment.java
> +    private long eventId;
Чтобы при маппинге в CommentDto без костылей или доп сборки могли мапится сущности эвента и автора

2022-10-02 17:37 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/Comment.java
> +    public boolean equals(Object o) {
привычка - всегда с помощью идеи генерировал эти методы)

2022-10-02 17:38 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/admin/CommentAdminController.java
> +    public CommentDto publishComment(@PathVariable long commentId) {
Согласен

2022-10-02 17:40 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/common/CommentPublicService.java
> +            return pageMaker.getPage(comments, pageable).getContent();
насчет PageMaker - у меня по какой-то причине раньше не работала пагинация в явном виде, поэтому у меня существует костыль в виде данного класса и метода
фильтрация по флагу positive - согласен, можно передавать в тело метода

2022-10-02 17:41 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/user/CommentUserService.java
> +        entityManager.refresh(comment);
без refresh не подгрузятся связанные сущности эвента и юзера

2022-10-02 17:42 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/event/Event.java
> +    private List<Compilation> compilations;
без этого поля не будет происходить запись эвентов в вспомогательную таблицу event_compilations

2022-10-02 17:44 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/common/CommentPublicService.java
> +            useful++;
Насколько я понимаю, ссылка будет дергать значения поля из БД, поэтому в самой модели я не менял значение

2022-10-02 17:44 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/user/CommentUserController.java
> +        mapper.map(commentUserService.getComment(dto.getId()), comment);
это очевидный костыль, надо переделать)

2022-10-02 17:45 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/common/CommentPublicService.java
> +        if (optionalComment.isEmpty()) {
согласен

2022-10-03 20:04 UTC, aturin236 approved these changes

2022-10-04 14:01 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/Comment.java
> +    public static Comment toEntity(NewCommentDto dto, long userId, long eventId) {
Comment -- доменный объект / DTO для бд. Лучше не связывать объекты между собой, а именно: доменный объект ничего не должен знать о том, как он будет использоваться. В частности, ему должно быть все равно на API и ему не следует знать про NewCommentDto совсем.

Представь, что ты бы программировал библиотеку. Стал бы ты добавлять в эту библиотеку поддержку всевозможных сценариев внешнего использования?

2022-10-04 14:02 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/CommentState.java
> +public enum CommentState {
[nit] ModerationStatus с возможными статусами PENDING, APPROVED, REJECTED?

2022-10-04 14:04 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/CommentState.java
> +public enum CommentState {
CommentState может относиться не только к модерации и было бы ошибкой добавлять сюда еще возможные значения, несвязанные с модерацией, потому что в таком случае нельзя будет проставить множество статусов на один объект.

Называя этот енам ModerationStatus ты обязываешь расширять этот енам только новыми статусами модерации, если таковые будет.

2022-10-04 14:19 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/CommentRepository.java
> +    void updateCommentStatus(CommentState state, long commentId);
[nit] я бы поменял местами аргументы

2022-10-04 14:21 UTC, vbutrim commented on server/src/main/resources/schema.sql
> +    UNIQUE (comment_id, user_id),
так будет создан индекс на (comment_id, user_id)?

может лучше PRIMARY KEY?

2022-10-04 14:23 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/user/CommentUserService.java
> +        commentRepository.rateComment(commentId, userId, isLike);
что будет при повторном лайке или попытке дизлайкнуть лайкнутый комментарий?

2022-10-04 14:52 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/user/CommentUserManager.java
> +public class CommentUserManager {
что означает User здесь?

2022-10-04 14:55 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/admin/CommentAdminService.java
> +        entityManager.refresh(comment);
пусть updateCommentStatus возвращает обновленный объект, тогда entityManager.refresh(comment) не нужен

2022-10-04 14:56 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/admin/CommentAdminService.java
> +        }
пусть метод принимает `ModerationStatus status`, тогда здесь будет `commentRepository.updateCommentStatus(commentId, status)`

2022-10-04 15:03 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/user/CommentUserService.java
> +        entityManager.refresh(comment);
ох этот hibernate
#save возвращает обновленный объект. мне каж-ся refresh не нужен

2022-10-04 15:05 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/user/CommentUserManager.java
> +public class CommentUserManager {
[nit] я понял идею сервиса и менеджера. сервис и менеджер являются синонимами. я бы перепридумал нейминг чутка.

может CommentService и Comment**Api**Manager?

2022-10-04 15:08 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/exception/EntityIsNotAvailableException.java
> +    public EntityIsNotAvailableException(String message) {
сообщение переиспользуется и генерируется заново каждый раз. формирование сообщение лучше вынести в сам класс на уровень конструктора, принимая необходимые айдишники в качестве аргументов

2022-10-04 15:08 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/common/CommentSort.java
> +public enum CommentSort {
[nit] CommentSortKey

2022-10-04 15:08 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/common/CommentPublicService.java
> +        Optional<Comment> optionalComment = commentRepository.findById(commentId);
[nit] можно просто `commentO`

2022-10-04 15:10 UTC, vbutrim requested changes
Андрей, оч крутая работа!

лайк за логирование
лайк за оперирование доменами в сервисе
лайк за API

оставил несколько улучшалок

2022-10-05 07:57 UTC, jokindy commented on server/src/main/resources/schema.sql
> +    UNIQUE (comment_id, user_id),
Сущность CommentLike подразумевается встраиваемой по отношению к сущности Comment и они соответствующим образом аннотированны @Embedded и @Embeddable и в этом случае нет необходимости в первичном ключе - напрямую к этой таблице не обратиться (по крайней мере в приложении)

2022-10-05 07:57 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/Comment.java
> +    public static Comment toEntity(NewCommentDto dto, long userId, long eventId) {
Соглашусь

2022-10-05 07:58 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/CommentState.java
> +public enum CommentState {
Хорошее замечание!

2022-10-05 07:58 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/CommentRepository.java
> +    void updateCommentStatus(CommentState state, long commentId);
Окей

2022-10-05 08:00 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/user/CommentUserService.java
> +        commentRepository.rateComment(commentId, userId, isLike);
приложение выкинет ошибку о нарушении уникальности пары значений commentId и userId от БД - лайк/дизлайк не сохранится. Как бы я улучшил: выкинул ошибку со стороны приложения, а не БД, для бОльшей информативности, пользователю не нужно знать, что там нарушается, а лучше видеть конкретную причину ошибки

2022-10-05 08:02 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/user/CommentUserManager.java
> +public class CommentUserManager {
уровень Api

2022-10-05 08:02 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/admin/CommentAdminService.java
> +        entityManager.refresh(comment);
согласен

2022-10-05 08:03 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/admin/CommentAdminService.java
> +        }
Хорошо

2022-10-05 08:03 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/user/CommentUserManager.java
> +public class CommentUserManager {
с неймингом у меня возникла проблема, поэтому назвал менеджером, хотя понимал, что масло масляное) идея с ApiManager мне нравится

2022-10-05 08:06 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/exception/EntityIsNotAvailableException.java
> +    public EntityIsNotAvailableException(String message) {
это исключение выкидывается в паре мест в приложении и принимает **разные** сообщения, поэтому я бы оставил все как есть. Альтернатива - еще один кастомный эксепшн

2022-10-05 08:06 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/common/CommentSort.java
> +public enum CommentSort {
окей

2022-10-05 08:06 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/common/CommentPublicService.java
> +        Optional<Comment> optionalComment = commentRepository.findById(commentId);
окей

2022-10-05 09:56 UTC, vbutrim commented on server/src/main/resources/schema.sql
> +    UNIQUE (comment_id, user_id),
поиск по такой таблице будет происходить за O(N) или по индексу?

2022-10-05 09:57 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/user/CommentUserService.java
> +        commentRepository.rateComment(commentId, userId, isLike);
Почему не рассматриваешь сценарий, что пользователь хочет изменить свою оценку? Поменять лайк на дизлайк?

Повторный лайк -- вполне себе реальный кейс. Два раза послать один и тот же реквест. Точно ли нужна ошибка?

2022-10-05 09:59 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/exception/EntityIsNotAvailableException.java
> +    public EntityIsNotAvailableException(String message) {
ты можешь принимать айдишники в качестве аргументов и собирать сообщение эксепшена в конструкторе.
дублирования стоит избегать

2022-10-05 15:40 UTC, jokindy commented on server/src/main/resources/schema.sql
> +    UNIQUE (comment_id, user_id),
Не задавался таким вопросом, по сценарию использования приложением этой таблице не предполагается поиск, только выгрузка всех значений для подсчета полезности. Отдельно лайк/дизлайк нигде не оперирует

2022-10-05 16:00 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/user/CommentUserService.java
> +        entityManager.refresh(comment);
Без него вылетает NPE из-за пустой таблицы с лайками

2022-10-05 16:15 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/admin/CommentAdminService.java
> +        entityManager.refresh(comment);
update - Modifying queries can only use void or int/Integer as return type

2022-10-05 20:06 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/admin/CommentAdminService.java
> +        entityManager.refresh(comment);
понял, не хочешь на более каноничный API переписать?
```
comment.setState(status);
return commentRepository.save(comment);
```

2022-10-05 20:07 UTC, jokindy commented on server/src/main/java/ru/practicum/explorewithme/comment/admin/CommentAdminService.java
> +        entityManager.refresh(comment);
сойдемся на этом

2022-10-05 20:09 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewithme/comment/admin/CommentAdminService.java
> +        entityManager.refresh(comment);
🤝

2022-10-06 10:44 UTC, vbutrim commented on stats/src/main/resources/application.properties
> +spring.datasource.password=iamroot
неслучайно?

2022-10-06 10:44 UTC, vbutrim commented on server/src/main/resources/application.properties
> +spring.datasource.password=iamroot
неслучайно?

2022-10-06 10:44 UTC, vbutrim approved these changes
космос!

2022-10-07 12:19 UTC, merged